### PR TITLE
Create explorersmystery.json

### PR DESCRIPTION
**Pull request by sokratis12GR**

### CODE REVIEW

**Comment by FayeAlephNil** [comment]
Please on the authors list surround the name with quotes. Thank you very much

**Comment by sokratis12GR** [comment]
ok, thanks for telling me this mistake, it wont happen again.

**Comment by sokratis12GR** [comment]
Is now alright ?

**Comment by FayeAlephNil** [comment]
No problem, and don't worry about it, small deal :P

Thank you very much

**Pull request merged**
